apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: communication-hub-svc
  name: communication-hub-svc
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: communication-hub-svc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: communication-hub-svc
    spec:
      containers:
      - image: nitinasati/communication-hub-svc:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: asatisamaj-matrimony-svc
        envFrom:
          - secretRef:
             name: communication-hub-svc-config
        readinessProbe: 
          httpGet:
            port: 8000
            path: /actuator/health/readiness
        livenessProbe: 
          httpGet:
            port: 8000
            path: /actuator/health/liveness
          initialDelaySeconds: 60
          periodSeconds: 10
      imagePullSecrets: 
        - name: regcred 
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: communication-hub-svc
  name: communication-hub-svc
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: communication-hub-svc
  sessionAffinity: None
  type: LoadBalancer